export const CHANGE_TRANSLATE_FROM_LANGUAGE = 'CHANGE_TRANSLATE_FROM_LANGUAGE';
export type CHANGE_TRANSLATE_FROM_LANGUAGE = typeof CHANGE_TRANSLATE_FROM_LANGUAGE;

export const CHANGE_TRANSLATE_TO_LANGUAGE = 'CHANGE_TRANSLATE_TO_LANGUAGE';
export type CHANGE_TRANSLATE_TO_LANGUAGE = typeof CHANGE_TRANSLATE_TO_LANGUAGE;
