export const CHANGE_TRANSLATE_FROM_LANGUAGE = 'CHANGE_TRANSLATE_FROM_LANGUAGE';
export type CHANGE_TRANSLATE_FROM_LANGUAGE = typeof CHANGE_TRANSLATE_FROM_LANGUAGE;

export const CHANGE_TRANSLATE_TO_LANGUAGE = 'CHANGE_TRANSLATE_TO_LANGUAGE';
export type CHANGE_TRANSLATE_TO_LANGUAGE = typeof CHANGE_TRANSLATE_TO_LANGUAGE;

export const SUBMIT_TRANSLATE = 'SUBMIT_TRANSLATE';
export type SUBMIT_TRANSLATE = typeof SUBMIT_TRANSLATE;
