export const CHANGE_TRANSLATE_FROM_LANGUAGE = 'CHANGE_TRANSLATE_FROM_LANGUAGE';
export type CHANGE_TRANSLATE_FROM_LANGUAGE = typeof CHANGE_TRANSLATE_FROM_LANGUAGE;

export const CHANGE_TRANSLATE_TO_LANGUAGE = 'CHANGE_TRANSLATE_TO_LANGUAGE';
export type CHANGE_TRANSLATE_TO_LANGUAGE = typeof CHANGE_TRANSLATE_TO_LANGUAGE;

export const SUBMIT_TRANSLATE = 'SUBMIT_TRANSLATE';
export type SUBMIT_TRANSLATE = typeof SUBMIT_TRANSLATE;

export const TRANSLATE_FROM_TEXT_CHANGE = 'TRANSLATE_FROM_TEXT_CHANGE';
export type TRANSLATE_FROM_TEXT_CHANGE = typeof TRANSLATE_FROM_TEXT_CHANGE;

export const TRANSLATE_TO_TEXT_CHANGE = 'TRANSLATE_TO_TEXT_CHANGE';
export type TRANSLATE_TO_TEXT_CHANGE = typeof TRANSLATE_TO_TEXT_CHANGE;

export const GET_TRANSLATION = 'GET_TRANSLATION';
export type GET_TRANSLATION = typeof GET_TRANSLATION;

export const GET_TRANSLATION_SUCCESS = 'GET_TRANSLATION_SUCCESS';
export type GET_TRANSLATION_SUCCESS = typeof GET_TRANSLATION_SUCCESS;